"""
Metrics — Perplexity Metric Module.
A standalone FastAPI service that computes HuggingFace perplexity
on text generated by the Module-3 pipeline.
"""

from fastapi import FastAPI
from router import router

app = FastAPI(
    title="HireVision — Perplexity Metric",
    description="Standalone service to compute perplexity (text fluency) on pipeline outputs using HuggingFace GPT-2.",
    version="1.0.0",
)

app.include_router(router, prefix="/perplexity")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8003)
