"""
Perplexity metric endpoints — computes HuggingFace perplexity on texts
generated by the Module-3 pipeline or on arbitrary raw text.
"""

import sys
from pathlib import Path

from fastapi import APIRouter

# Add parent Metrics dir to path so we can import the shared pipeline client
sys.path.insert(0, str(Path(__file__).parent.parent))

import pipeline_client
import perplexity_scorer
from models import (
    PipelinePerplexityRequest,
    TextPerplexityRequest,
    PipelinePerplexityResponse,
    TextPerplexityResponse,
    CategoryPerplexity,
)

router = APIRouter()


@router.post("/pipeline", response_model=PipelinePerplexityResponse)
async def perplexity_pipeline(req: PipelinePerplexityRequest):
    """
    Runs the full Module-3 pipeline (Question-Gen + Answer-Eval),
    collects all generated text, and computes perplexity by category.
    """

    # 1. Fetch questions + answers from the pipeline
    qa_pairs = await pipeline_client.fetch_questions_with_answers(
        job_title=req.job_title,
        skills=req.skills,
        experience_level=req.experience_level,
        num_questions=req.num_questions,
    )

    # 2. Collect texts by category
    question_texts = [item["question"] for item in qa_pairs]
    # Skip MCQ answers — they are just single letters (A/B/C/D), not real text
    answer_texts = [
        item.get("reference_answer") or ""
        for item in qa_pairs
        if item.get("question_type", "").lower() != "mcq"
    ]
    # Filter out empty answers
    answer_texts = [t for t in answer_texts if t.strip()]

    # 3. Compute perplexity per category
    categories = []

    if question_texts:
        q_result = perplexity_scorer.compute_perplexity(
            texts=question_texts, model_id=req.model_id
        )
        categories.append(CategoryPerplexity(
            category="questions",
            texts=question_texts,
            perplexities=q_result["perplexities"],
            mean_perplexity=q_result["mean_perplexity"],
        ))

    if answer_texts:
        a_result = perplexity_scorer.compute_perplexity(
            texts=answer_texts, model_id=req.model_id
        )
        categories.append(CategoryPerplexity(
            category="answers",
            texts=answer_texts,
            perplexities=a_result["perplexities"],
            mean_perplexity=a_result["mean_perplexity"],
        ))

    # 4. Compute overall
    all_perplexities = []
    for cat in categories:
        all_perplexities.extend(cat.perplexities)

    overall_mean = (
        round(sum(all_perplexities) / len(all_perplexities), 2)
        if all_perplexities else 0.0
    )

    return PipelinePerplexityResponse(
        categories=categories,
        all_perplexities=all_perplexities,
        overall_mean_perplexity=overall_mean,
        model_id=req.model_id,
    )


@router.post("/text", response_model=TextPerplexityResponse)
async def perplexity_text(req: TextPerplexityRequest):
    """
    Computes perplexity on arbitrary raw text input.
    """
    result = perplexity_scorer.compute_perplexity(
        texts=req.texts, model_id=req.model_id
    )

    valid_texts = [t for t in req.texts if t and t.strip()]

    return TextPerplexityResponse(
        texts=valid_texts,
        perplexities=result["perplexities"],
        mean_perplexity=result["mean_perplexity"],
        model_id=req.model_id,
    )
