services:
  mongodb:
    image: mongo:7-jammy
    container_name: mongodb
    ports:
      - "27017:27017"
      # - "27007:27017"
    volumes:
      - ./mongo-data:/data/db      # <--- bind mount to project folder
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - backend
    restart: always

networks:
  backend:

# remove named volumes if you only use bind mount
# volumes:
#   mongodata:
