"""
Pydantic models for the Model Selection metric.
"""
from pydantic import BaseModel, Field

class ModelSelectionRequest(BaseModel):
    """
    Request to find the best model for a given job context.
    """
    job_title: str = Field(description="Target job role")
    skills: list[str] = Field(description="Required skills for the role")
    experience_level: str = Field(description="Experience level (Junior, Mid, Senior)")
    num_questions: int = Field(default=5, ge=1, description="Number of questions to generate per model")
    # We do NOT ask for model_key, because the purpose is to test ALL models.


class ModelRanking(BaseModel):
    """
    Performance metrics for a specific model.
    """
    model_key: str
    mean_perplexity: float
    perplexities: list[float]
    sample_questions: list[str] = Field(description="Sample questions generated by this model")


class ModelSelectionResponse(BaseModel):
    """
    Response containing the ranking of models.
    """
    best_model: str = Field(description="Key of the model with the lowest mean perplexity")
    rankings: list[ModelRanking] = Field(description="List of models sorted by perplexity (ascending)")
    job_title: str
